/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-10-04 at 04:45:11 UTC 
 * Modify at your own risk.
 */

package com.tfl.entity.billendpoint.model;

/**
 * Model definition for Bill.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the billendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Bill extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String billDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String billGeneratedBy;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Contact contact;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double finalAmount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String jobDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numberOfHours;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String payableTo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Rates rate;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBillDate() {
    return billDate;
  }

  /**
   * @param billDate billDate or {@code null} for none
   */
  public Bill setBillDate(java.lang.String billDate) {
    this.billDate = billDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBillGeneratedBy() {
    return billGeneratedBy;
  }

  /**
   * @param billGeneratedBy billGeneratedBy or {@code null} for none
   */
  public Bill setBillGeneratedBy(java.lang.String billGeneratedBy) {
    this.billGeneratedBy = billGeneratedBy;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Contact getContact() {
    return contact;
  }

  /**
   * @param contact contact or {@code null} for none
   */
  public Bill setContact(Contact contact) {
    this.contact = contact;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getFinalAmount() {
    return finalAmount;
  }

  /**
   * @param finalAmount finalAmount or {@code null} for none
   */
  public Bill setFinalAmount(java.lang.Double finalAmount) {
    this.finalAmount = finalAmount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getJobDescription() {
    return jobDescription;
  }

  /**
   * @param jobDescription jobDescription or {@code null} for none
   */
  public Bill setJobDescription(java.lang.String jobDescription) {
    this.jobDescription = jobDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public Bill setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumberOfHours() {
    return numberOfHours;
  }

  /**
   * @param numberOfHours numberOfHours or {@code null} for none
   */
  public Bill setNumberOfHours(java.lang.Integer numberOfHours) {
    this.numberOfHours = numberOfHours;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPayableTo() {
    return payableTo;
  }

  /**
   * @param payableTo payableTo or {@code null} for none
   */
  public Bill setPayableTo(java.lang.String payableTo) {
    this.payableTo = payableTo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Rates getRate() {
    return rate;
  }

  /**
   * @param rate rate or {@code null} for none
   */
  public Bill setRate(Rates rate) {
    this.rate = rate;
    return this;
  }

  @Override
  public Bill set(String fieldName, Object value) {
    return (Bill) super.set(fieldName, value);
  }

  @Override
  public Bill clone() {
    return (Bill) super.clone();
  }

}
