/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-10-04 at 04:45:15 UTC 
 * Modify at your own risk.
 */

package com.tfl.entity.ratesendpoint;

/**
 * Service definition for Ratesendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link RatesendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Ratesendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the ratesendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://BillGen.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "ratesendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Ratesendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Ratesendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getRates".
   *
   * This request holds the parameters needed by the ratesendpoint server.  After setting any optional
   * parameters, call the {@link GetRates#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetRates getRates(java.lang.String id) throws java.io.IOException {
    GetRates result = new GetRates(id);
    initialize(result);
    return result;
  }

  public class GetRates extends RatesendpointRequest<com.tfl.entity.ratesendpoint.model.Rates> {

    private static final String REST_PATH = "rates/{id}";

    /**
     * Create a request for the method "getRates".
     *
     * This request holds the parameters needed by the the ratesendpoint server.  After setting any
     * optional parameters, call the {@link GetRates#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetRates#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetRates(java.lang.String id) {
      super(Ratesendpoint.this, "GET", REST_PATH, null, com.tfl.entity.ratesendpoint.model.Rates.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetRates setAlt(java.lang.String alt) {
      return (GetRates) super.setAlt(alt);
    }

    @Override
    public GetRates setFields(java.lang.String fields) {
      return (GetRates) super.setFields(fields);
    }

    @Override
    public GetRates setKey(java.lang.String key) {
      return (GetRates) super.setKey(key);
    }

    @Override
    public GetRates setOauthToken(java.lang.String oauthToken) {
      return (GetRates) super.setOauthToken(oauthToken);
    }

    @Override
    public GetRates setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetRates) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetRates setQuotaUser(java.lang.String quotaUser) {
      return (GetRates) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetRates setUserIp(java.lang.String userIp) {
      return (GetRates) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetRates setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetRates set(String parameterName, Object value) {
      return (GetRates) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertRates".
   *
   * This request holds the parameters needed by the ratesendpoint server.  After setting any optional
   * parameters, call the {@link InsertRates#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.tfl.entity.ratesendpoint.model.Rates}
   * @return the request
   */
  public InsertRates insertRates(com.tfl.entity.ratesendpoint.model.Rates content) throws java.io.IOException {
    InsertRates result = new InsertRates(content);
    initialize(result);
    return result;
  }

  public class InsertRates extends RatesendpointRequest<com.tfl.entity.ratesendpoint.model.Rates> {

    private static final String REST_PATH = "rates";

    /**
     * Create a request for the method "insertRates".
     *
     * This request holds the parameters needed by the the ratesendpoint server.  After setting any
     * optional parameters, call the {@link InsertRates#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertRates#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.tfl.entity.ratesendpoint.model.Rates}
     * @since 1.13
     */
    protected InsertRates(com.tfl.entity.ratesendpoint.model.Rates content) {
      super(Ratesendpoint.this, "POST", REST_PATH, content, com.tfl.entity.ratesendpoint.model.Rates.class);
    }

    @Override
    public InsertRates setAlt(java.lang.String alt) {
      return (InsertRates) super.setAlt(alt);
    }

    @Override
    public InsertRates setFields(java.lang.String fields) {
      return (InsertRates) super.setFields(fields);
    }

    @Override
    public InsertRates setKey(java.lang.String key) {
      return (InsertRates) super.setKey(key);
    }

    @Override
    public InsertRates setOauthToken(java.lang.String oauthToken) {
      return (InsertRates) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertRates setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertRates) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertRates setQuotaUser(java.lang.String quotaUser) {
      return (InsertRates) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertRates setUserIp(java.lang.String userIp) {
      return (InsertRates) super.setUserIp(userIp);
    }

    @Override
    public InsertRates set(String parameterName, Object value) {
      return (InsertRates) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listRates".
   *
   * This request holds the parameters needed by the ratesendpoint server.  After setting any optional
   * parameters, call the {@link ListRates#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListRates listRates() throws java.io.IOException {
    ListRates result = new ListRates();
    initialize(result);
    return result;
  }

  public class ListRates extends RatesendpointRequest<com.tfl.entity.ratesendpoint.model.CollectionResponseRates> {

    private static final String REST_PATH = "rates";

    /**
     * Create a request for the method "listRates".
     *
     * This request holds the parameters needed by the the ratesendpoint server.  After setting any
     * optional parameters, call the {@link ListRates#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListRates#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListRates() {
      super(Ratesendpoint.this, "GET", REST_PATH, null, com.tfl.entity.ratesendpoint.model.CollectionResponseRates.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListRates setAlt(java.lang.String alt) {
      return (ListRates) super.setAlt(alt);
    }

    @Override
    public ListRates setFields(java.lang.String fields) {
      return (ListRates) super.setFields(fields);
    }

    @Override
    public ListRates setKey(java.lang.String key) {
      return (ListRates) super.setKey(key);
    }

    @Override
    public ListRates setOauthToken(java.lang.String oauthToken) {
      return (ListRates) super.setOauthToken(oauthToken);
    }

    @Override
    public ListRates setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListRates) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListRates setQuotaUser(java.lang.String quotaUser) {
      return (ListRates) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListRates setUserIp(java.lang.String userIp) {
      return (ListRates) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListRates setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListRates setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListRates set(String parameterName, Object value) {
      return (ListRates) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeRates".
   *
   * This request holds the parameters needed by the ratesendpoint server.  After setting any optional
   * parameters, call the {@link RemoveRates#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveRates removeRates(java.lang.String id) throws java.io.IOException {
    RemoveRates result = new RemoveRates(id);
    initialize(result);
    return result;
  }

  public class RemoveRates extends RatesendpointRequest<Void> {

    private static final String REST_PATH = "rates/{id}";

    /**
     * Create a request for the method "removeRates".
     *
     * This request holds the parameters needed by the the ratesendpoint server.  After setting any
     * optional parameters, call the {@link RemoveRates#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveRates#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveRates(java.lang.String id) {
      super(Ratesendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveRates setAlt(java.lang.String alt) {
      return (RemoveRates) super.setAlt(alt);
    }

    @Override
    public RemoveRates setFields(java.lang.String fields) {
      return (RemoveRates) super.setFields(fields);
    }

    @Override
    public RemoveRates setKey(java.lang.String key) {
      return (RemoveRates) super.setKey(key);
    }

    @Override
    public RemoveRates setOauthToken(java.lang.String oauthToken) {
      return (RemoveRates) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveRates setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveRates) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveRates setQuotaUser(java.lang.String quotaUser) {
      return (RemoveRates) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveRates setUserIp(java.lang.String userIp) {
      return (RemoveRates) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveRates setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveRates set(String parameterName, Object value) {
      return (RemoveRates) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateRates".
   *
   * This request holds the parameters needed by the ratesendpoint server.  After setting any optional
   * parameters, call the {@link UpdateRates#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.tfl.entity.ratesendpoint.model.Rates}
   * @return the request
   */
  public UpdateRates updateRates(com.tfl.entity.ratesendpoint.model.Rates content) throws java.io.IOException {
    UpdateRates result = new UpdateRates(content);
    initialize(result);
    return result;
  }

  public class UpdateRates extends RatesendpointRequest<com.tfl.entity.ratesendpoint.model.Rates> {

    private static final String REST_PATH = "rates";

    /**
     * Create a request for the method "updateRates".
     *
     * This request holds the parameters needed by the the ratesendpoint server.  After setting any
     * optional parameters, call the {@link UpdateRates#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateRates#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.tfl.entity.ratesendpoint.model.Rates}
     * @since 1.13
     */
    protected UpdateRates(com.tfl.entity.ratesendpoint.model.Rates content) {
      super(Ratesendpoint.this, "PUT", REST_PATH, content, com.tfl.entity.ratesendpoint.model.Rates.class);
    }

    @Override
    public UpdateRates setAlt(java.lang.String alt) {
      return (UpdateRates) super.setAlt(alt);
    }

    @Override
    public UpdateRates setFields(java.lang.String fields) {
      return (UpdateRates) super.setFields(fields);
    }

    @Override
    public UpdateRates setKey(java.lang.String key) {
      return (UpdateRates) super.setKey(key);
    }

    @Override
    public UpdateRates setOauthToken(java.lang.String oauthToken) {
      return (UpdateRates) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateRates setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateRates) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateRates setQuotaUser(java.lang.String quotaUser) {
      return (UpdateRates) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateRates setUserIp(java.lang.String userIp) {
      return (UpdateRates) super.setUserIp(userIp);
    }

    @Override
    public UpdateRates set(String parameterName, Object value) {
      return (UpdateRates) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Ratesendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Ratesendpoint}. */
    @Override
    public Ratesendpoint build() {
      return new Ratesendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link RatesendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setRatesendpointRequestInitializer(
        RatesendpointRequestInitializer ratesendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(ratesendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
